version: '3.1'
services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    container_name: redis-server
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
volumes:
  db:
  redis: